### ISSUE TITLE
Please optimize the usage of docker version

### ISSUE THREAD

**Issue by mixiaoluo88** [zhenchengfang/metaProbiotics#1]
Hello, thank you for creating such excellent software. 

  However, I have encountered some issues while using the software and would appreciate it if you could optimize its usage. 

  Firstly, the tutorial does not include a command to pull the Docker image (that is not a big deal). I managed to find the 1.0 version of the MetaProbiotics image provided by Shufangwu on Docker Hub `docker pull shufangwu/metaprobiotics:1.0`. As shown in the demo, we can interact with the software, but I noticed that when I use the `run` command in docker, the LD_LIBRARY_PATH variables are missing. The error message show this info `/home/metaProbiotics/metaProbiotics:error while loading shared libraries:libmwlaunchermain.so:cannot open shared object file:No such file or directory`

  Additionally, even when I manually add the variables, I am unable to run the software using an absolute path, which results in the software being unable to locate jellyfish-linux. My assumption is that this may be due to the software being coded to pass variables in the form of relative paths. I would greatly appreciate it if you could make the necessary changes and optimizations to the software promptly.

To assist other users who wish to run the software in hpc, I have provided a solution for the Docker 1.0 version:
`docker run --rm -i -v /local/wkdir/to/genomes:/mnt/genomes shufangwu/metaprobiotics:1.0 /bin/bash -c 'export LD_LIBRARY_PATH=/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/bin/glnxa64; cd /home/metaProbiotics; ./metaProbiotics /mnt/genomes/test.fna /mnt/genomes/test.txt'`

Hongyang lvy

**Comment by zhenchengfang** [comment]
Hi, Hongyang lvy. Thank you for your detailed feedback, we will try to make some adjustments for the docker version within the next two weeks, and the updated version will be posted on github. You can also use the virtual machine version of meteProbiotics, which is easier to use directly on a personal laptop.

**Comment by mixiaoluo88** [comment]
@zhenchengfang Thank you for your prompt response. I will consider trying the virtual machine version in the future. 

Since the issue has been identified, I will go ahead and close this comment. 

Thanks once again for your quick reply.

**Comment by zhenchengfang** [comment]
Hi, Hongyang lvy. Thank you again for your suggestion. Based on our check, we found that you may be using metaProbiotics outside of the docker container. If you use metaProbiotics inside the container according to the instructions in our manual, you will not need to configure environment variables. Actually, we suggest you use metaProbiotics according to the manual, as it introduces detailed steps including how to download the image of metaProbiotics.
